# Generated by Django 5.2 on 2025-04-14 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='catalog',
        ),
    ]
