# Generated by Django 5.2 on 2025-06-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_userprofile_delete_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/media/avatars/default_avatar.png', upload_to='avatars/'),
        ),
    ]
